project_id = "xlrlelzqasgqaiylldcj"

[functions.ai-chat]
verify_jwt = false

[functions.parent-auth]
verify_jwt = false

[functions.parent-data]
verify_jwt = false

[functions.paydunya-checkout]
verify_jwt = false

[functions.paydunya-webhook]
verify_jwt = false
