project_id = "xlrlelzqasgqaiylldcj"

[functions.ai-chat]
verify_jwt = false

[functions.parent-auth]
verify_jwt = false

[functions.parent-data]
verify_jwt = false

[functions.paydunya-checkout]
verify_jwt = false

[functions.paydunya-webhook]
verify_jwt = false

[functions.cantine-ordre]
verify_jwt = false

[functions.student-auth]
verify_jwt = false

[functions.student-data]
verify_jwt = false

[functions.student-submit]
verify_jwt = false

[functions.employee-auth]
verify_jwt = false

[functions.employee-data]
verify_jwt = false

[functions.credit-reminders]
verify_jwt = false
